# spell-checker:ignore DCMAKE
name: Build
description: Build the project with CMake

inputs:
  only-compile-commands:
    description: Simulate a build for the sole purpose of generating a compilation database
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4

    - name: Install requirements
      shell: bash
      run: |
        sudo apt-get update -qq
        sudo apt-get install cmake -qq

    - name: Build
      shell: bash
      run: |
        echo ${{inputs.only-compile-commands}}
        cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL:=TRUE -DCMAKE_BUILD_TYPE:STRING:=Release
        if [[ ${{inputs.only-compile-commands}} != "true" ]]; then \
          cmake --build build --config Release; \
        fi
        cp build/compile_commands.json .
