# spell-checker:ignore DCMAKE
name: Build

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
  workflow_call:
    inputs:
      only-compile-commands:
        description: Simulate a build for the sole purpose of generating a compilation database
        required: false
        type: boolean
        default: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install requirements
        run: |
          sudo apt-get update -qq
          sudo apt-get install cmake -qq

      - name: Build
        run: |
          cmake -S . -B build -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL:=TRUE -DCMAKE_BUILD_TYPE:STRING:=Release
          if [[ {{inputs.only-compile-commands}} != true ]]; then \
            cmake --build build --config Release; \
          fi
          cp build/compile_commands.json .
