name: cpp-linter

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate compilation database
        run: |
          sudo apt-get update
          # Inefficient: installing clang twice, but there's not much of a viable workaround
          sudo apt-get install bear clang libgtest-dev -y
          make compile_commands debug=true
          cat compile_commands.json
      - uses: Terracom12/cpp-linter-action@main
        id: linter
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: file
          version: 18
          # verbosity: 'debug'
          files-changed-only: false
          file-annotations: true
          thread-comments: false
          tidy-checks: ""
          step-summary: true

      - name: Fail fast?!
        if: steps.linter.outputs.checks-failed != 0
        # run: |
        #  echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
        # for actual deployment
        run: exit 1
