name: Lint

on:
  # push:
  #   branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: LLVM Dependencies
        uses: aminya/setup-cpp@v1
        with:
          cppcheck: true
          clangtidy: 17
          clangformat: 17

      - uses: ./.github/actions/setup
        with:
          only-compile-commands: "true"

      - name: Run linters
        run: ./scripts/lint.sh
